site_name: Dr. Inventor Text Mining Framework Documentation
repo_url: https://github.com/fra82/driframework
repo_name: GitHub
theme: readthedocs
site_description: Documentation for Dr. Inventor Text Mining Framework
docs_dir: doc
include_search: true
pages:
- ['index.md', 'Home']
- ['Introduction.md', 'About', 'Introduction']
- ['References.md', 'About', 'References']
- ['Version.md', 'About', 'Version']
- ['ArchitectureOverview.md', 'Architecture', 'Overview']
- ['PDFtoText.md', 'Architecture', 'PDF to text converter']
- ['Citation.md', 'Architecture', 'Citation analyzer']
- ['RhetSentence.md', 'Architecture', 'Rhetorical sentence classifier']
- ['BabelnetAnn.md', 'Architecture', 'Babelnet annotator']
- ['SVOgraph.md', 'Architecture', 'Subject-Verb-Object graph generator']
- ['Summa.md', 'Architecture', 'Document summarizer']
- ['Installation.md', 'User manual', 'Installation']
- ['Initialize.md', 'User manual', 'Initialization']
- ['ImportDoc.md', 'User manual', 'Import scientific publications']
- ['ProcessDoc.md', 'User manual', 'Process scientific publications']
- ['ScuPubDataModel.md', 'User manual', 'The Scientific Publication Data Model']
- ['StoreDoc.md', 'User manual', 'Store processing results']
- ['FAQ.md', 'User manual', 'FAQ']
