site_name: Dr. Inventor Text Mining Framework Documentation
repo_url: https://github.com/fra82/driframework
repo_name: GitHub
theme: readthedocs
site_description: Documentation for Dr. Inventor Text Mining Framework
docs_dir: doc
include_search: true
pages:
- ['index.md', 'Home']
- ['Introduction.md', 'About', 'Introduction']
- ['References.md', 'About', 'References']
- ['Version.md', 'About', 'Version']
- ['Components.md', 'Architecture', 'Overview']
- ['PDFtoText.md', 'Architecture', 'PDF to text converter']
- ['Installation.md', 'User manual', 'Installation']
